name: CS313
description: A Streamlit application for analyzing hurricane trajectories, visualizing patterns, and predicting hurricane categories.
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - pactus
    - streamlit
    - matplotlib
    - cartopy
    - yupi
    - numpy
    - pandas
    - xgboost
    - seaborn
    - scikit-learn
    - plotly
